[package]
name = "pwg"
version = "0.1.0"
authors = ["yukimemi <yukimemi@gmail.com>"]
description = "password generator"
edition = "2018"

[dependencies]
failure = "0.1.5"
pretty_env_logger = "0.3.0"
log = "0.4.6"
clap = "4.0.0"
passwords = "1.1.2"
clipboard = "0.5.0"
